config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, :soups
  root "categories#index"
  get "/allcategories", to: redirect("/")
  get "soup/:id/toggle_featured", to: "soups#toggle_featured", as: :toggle_featured
  get "/secret_soups" ,to: "soups#secret_soups"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :soups
end

app/models/soup.rb
class Soup < ApplicationRecord
	belongs_to :category
	validates :name, presence: true ,
	                uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
		
	end
	def show
		@category = Category.find(params[:id])
	end
end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
	before_action :fetch_soup, only: [:show, :edit, :update, :destroy, :toggle_featured]
	def show
		respond_to do |format|
			format.html
			format.json {render json: @soup}
		end
	end
	def index
		@soups = Soup.all
		respond_to do |format|
			format.json {render json: @soups}
		end
	end
	def toggle_featured
		@soup.toggle!(:featured)
		flash[:notice] = "successfully changed the featured"
		redirect_to @soup
	end
	def secret_soups
		session[:vip] = true
		redirect_to root_path
	end
	private
	def fetch_soup
		@soup = Soup.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/views/categories/index.html.erb
<h2>Soup Categories</h2>
<ul>
	<% @categories.each do |category| %>
	<li><%= link_to category.name, category%>(<%= category.soups.count %>)</li>
	<% end %>
	<% if session[:vip] %>
	<li>secret soup</li>
	<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name%></h1>
<ul>
	<% @category.soups.each do |soup|%>
	<li><%= link_to soup.name , soup %></li>
	<% end %>
	
</ul>
<p><%= link_to "Back to Categories", categories_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoupToBits</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice] %>
  <p><%= flash[:notice]%></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/soups/show.html.erb
<h1><%= @soup.name%></h1>

<% if @soup.featured? %>
<p>This soup is available</p>
<% else %>
<p>This soup is not Available</p>
<% end %>
<% if params[:admin] == "true" %>
<p><%= link_to "Toggle Featured" , toggle_featured_path(@soup)%></p>
<% end %>